# Generated by Django 5.1.5 on 2026-07-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_url_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_qr_only',
            field=models.BooleanField(default=False),
        ),
    ]
