# Generated by Django 5.1.5 on 2026-07-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_url_is_qr_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
