# Generated by Django 5.1.5 on 2026-07-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_alter_url_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
